### ISSUE TITLE
question regarding evolution of the phase of the fundamental mode

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/olive#1]
A question was posed during the poster session at the SRF17 conference in Lanzhou, which I was unable to answer:

During beam loading, does the phase of the fundamental harmonic evolve such that it differs significantly from what is seen in the absence of beam loading?

**Comment by dtabell** [comment]
My knee jerk reaction is no. But I did never actually explored that question. Will do so today.

**Comment by dtabell** [comment]
Yes, it does. There are two ways to see this:
(1) During the field update, the algorithm simply rotates each eigenmode according to it's eigenfrequency. But during the particle-coupling (PC) update, the mode momentum gets kicked. This step, see eq.(23b) in our paper
https://journals.aps.org/prab/abstract/10.1103/PhysRevAccelBeams.20.052002
does not occur unless there is beam loading. And it is this step that causes the phase to slip relative to the unloaded cavity.
(2) Based on the Hamiltonian H_f—see the second term in eq.(10)—you can compute the phase as arg( Q / sqrt(L) + i P / sqrt(C) ). Here Q and P denote the phase-space coordinates for the mode of interest; and L and C denote (again for the mode of interest) the mode inductance and capacitance defined at the bottom of the left-hand column on page 3 of our paper. A plot of the phase evolution looks nearly linear, as it should, but a plot of the phase difference, so φ_(n+1) - φ_n vs n, where n denotes the time-step., reveals a phase slip.

**Comment by bruhwiler** [comment]
Thanks!
